name: Publish Firmware to dist Branch

on:
  workflow_run:
    workflows: ["Build ESP32 Firmware"]
    types: [completed]
  workflow_dispatch:

jobs:
  publish:
    name: Generate Manifest and Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GitHub CLI
        run: sudo apt-get install -y gh jq

      - name: Download all artifacts from triggering workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          RUN_ID: ${{ github.event.workflow_run.id }}
        run: |
          mkdir -p dist
          echo "Downloading artifacts from workflow run $RUN_ID"
          gh run download $RUN_ID --repo "$OWNER/$REPO" --dir dist

      - name: Generate manifest.json
        run: ./build_manifest.sh dist

      - name: Deploy to dist branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: dist
          force_orphan: true
